version: '3.1'
services:
  python-logger:
    container_name: pylogger
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./setup.cfg:/var/app/setup.cfg
      - ./tests:/var/app/tests
      - ./pylogger:/var/app/pylogger
    ports:
      - 5000:5000
    environment:
      TZ: Asia/Tokyo
    tty: true
