name: Run pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install poetry and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry --upgrade-strategy=only-if-needed
        poetry config virtualenvs.create false
        poetry install
    - name: Save cache
      uses: actions/cache@v1
      with:
        path: |
          /usr/local/bin
          /usr/local/lib/python3.7/site-packages
        key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Run test
      run: |
        poetry run pytest .
